### ISSUE TITLE
compilation error when dealing with the Kernel

### ISSUE THREAD

**Issue by leonardowolf** [unframework/licheepi-nano-buildroot#18] opened 2022-08-18 14:49 UTC
I'm guessing that since the kernel got updated, the default scripts which were "hard-coded" to k 5.4 won't work anymore 

```
INSTALL /home/munin/Projecs/lichee_project/unf_buildroot/buildroot-2022.05.1/output/build/linux-headers-v5.11-nano-3/usr/include
>>> linux-headers v5.11-nano-3 Building
>>> linux-headers v5.11-nano-3 Installing to staging directory
(cd /home/munin/Projecs/lichee_project/unf_buildroot/buildroot-2022.05.1/output/build/linux-headers-v5.11-nano-3; PATH="/home/munin/Projecs/lichee_project/unf_buildroot/buildroot-2022.05.1/output/host/bin:/home/munin/Projecs/lichee_project/unf_buildroot/buildroot-2022.05.1/output/host/sbin:/home/munin/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabi/bin" /usr/bin/make  ARCH=arm HOSTCC="/usr/bin/gcc" HOSTCFLAGS="" HOSTCXX="/usr/bin/g++" INSTALL_HDR_PATH=/home/munin/Projecs/lichee_project/unf_buildroot/buildroot-2022.05.1/output/host/arm-buildroot-linux-gnueabi/sysroot/usr headers_install)
  INSTALL /home/munin/Projecs/lichee_project/unf_buildroot/buildroot-2022.05.1/output/host/arm-buildroot-linux-gnueabi/sysroot/usr/include
if ! support/scripts/check-kernel-headers.sh  /home/munin/Projecs/lichee_project/unf_buildroot/buildroot-2022.05.1/output/build  /home/munin/Projecs/lichee_project/unf_buildroot/buildroot-2022.05.1/output/host/arm-buildroot-linux-gnueabi/sysroot  5.4 strict; then exit 1; fi
Incorrect selection of kernel headers: expected 5.4.x, got 5.11.x
make[1]: *** [package/pkg-generic.mk:333: /home/munin/Projecs/lichee_project/unf_buildroot/buildroot-2022.05.1/output/build/linux-headers-v5.11-nano-3/.stamp_staging_installed] Error 1
make: *** [Makefile:84: _all] Error 2

```
I'm trying to solve that one myself too, but any help would be appreciated

**Comment by unframework** [comment] 2022-08-18 17:26
Hi Leonardo, yes please update with results if you find something. I am slowly working through my open source issues backlog currently (had a bit of an overloaded summer!), and will try to get to the Lichee Pi related stuff in the next couple weeks.

**Comment by peterbmckinley** [comment] 2022-12-27 16:50
Incorrect selection of kernel headers: expected 5.4.x, got 5.11.x

whats the solution to this?

**Comment by peterbmckinley** [comment] 2022-12-27 17:04
Should be as follows:

make menuconfig > Custom kernel headers series (5.4.x)  ---> > change from 5.4.x to 5.11.x and save

Building now, I'll close when I've confirmed the build completes

**Comment by peterbmckinley** [comment] 2022-12-28 12:36
Hi I can confirm this builds OK once the header is updated as described. I would be grateful if the maintainer could update the repo and close this ticket.

Thanks in advance

Peter

**Comment by unframework** [comment] 2022-12-30 00:24
Thanks for looking into this! Since these issues are due to updated Buildroot version I will try to find a time to update my local install as well and incorporate the above changes. For now, I will tweak the docs to mention these caveats.

**Comment by peterbmckinley** [comment] 2022-12-30 00:29
Thanks Nick. Would you be interested in collaborating on a project of mine?

https://github.com/speedsaver

Peter

**Comment by unframework** [comment] 2022-12-30 00:55
Hi @peterbmckinley, thanks for the invite! I am not currently working with embedded boards much, and generally a bit stretched with work unfortunately. Are you building a new devboard?

**Comment by peterbmckinley** [comment] 2022-12-31 12:58
Hi Nick,

I did commission my own board based on the Allwinner V3LP (new Low Power
drop in replacement for V3s), however costings for UK production for 1k
units came in WAY over target and I can't overcome that hurdle. So I open
sourced the PCB production files on my Speedsaver Github organisation.

The board was only ever a platform for my code, which is the core use case,
an aftermarket automotive safety device.

My code runs on Orange Pi Zero and Lichee Zero. But for maximum cost
savings I'm looking to partner with someone who can maintain my mature and
working code and also port to Lichee Nano. Obviously you have considerable
knowledge of this board.

I know the code works on the MangoPi R3c, which uses an F1C200s SoC, and my
ram overhead is within spec for the 32 MByte F1C100s. So technically
porting the code should be fairly straightforward, although some late
commit appears to have broken the build. I'll see if I can get Steve my
former contributor to fix that, it was working before.

Let me know if this is something you would be interested to discuss. My
email is ***@***.***

Regards

Peter McKinley

Speedsaver Ltd

**Closed** 2023-12-18 06:28 UTC
